tbl을 사용해보자
tbl은 저장하거나 보관하는데 편리하다.

In [1]:
data(diamonds, package="ggplot2")

In [2]:
class(diamonds)

[1] "tbl_df"     "tbl"        "data.frame"

In [3]:
library(dplyr)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [4]:
dia <- as.tbl(diamonds)
# tbl은 데이터 프레임이지만 좀더 편리한 데이터 프레임이다.

Warning message:
“`as.tbl()` was deprecated in dplyr 1.0.0.
Please use `tibble::as_tibble()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated.”

In [7]:
dia[, c('carat', 'price')]

      carat price
1     0.23  326
2     0.21  326
3     0.23  327
4     0.29  334
5     0.31  335
6     0.24  336
7     0.24  336
8     0.26  337
9     0.22  337
10    0.23  338
11    0.30  339
12    0.23  340
13    0.22  342
14    0.31  344
15    0.20  345
16    0.32  345
17    0.30  348
18    0.30  351
19    0.30  351
20    0.30  351
21    0.30  351
22    0.23  352
23    0.23  353
24    0.31  353
25    0.31  353
26    0.23  354
27    0.24  355
28    0.30  357
29    0.23  357
30    0.23  357
⋮     ⋮     ⋮
53911 0.70  2753
53912 0.57  2753
53913 0.61  2753
53914 0.80  2753
53915 0.84  2753
53916 0.77  2753
53917 0.74  2753
53918 0.90  2753
53919 0.76  2753
53920 0.76  2753
53921 0.70  2755
53922 0.70  2755
53923 0.70  2755
53924 0.73  2756
53925 0.73  2756
53926 0.79  2756
53927 0.71  2756
53928 0.79  2756
53929 0.79  2756
53930 0.71  2756
53931 0.71  2756
53932 0.71  2756
53933 0.70  2757
53934 0.70  2757
53935 0.72  2757
53936 0.72  2757
53937 0.72  2757
53938 0.70  2757
53939 0.86  2757
53940 0.75  2757

In [8]:
dia %>% select(carat, price)

      carat price
1     0.23  326
2     0.21  326
3     0.23  327
4     0.29  334
5     0.31  335
6     0.24  336
7     0.24  336
8     0.26  337
9     0.22  337
10    0.23  338
11    0.30  339
12    0.23  340
13    0.22  342
14    0.31  344
15    0.20  345
16    0.32  345
17    0.30  348
18    0.30  351
19    0.30  351
20    0.30  351
21    0.30  351
22    0.23  352
23    0.23  353
24    0.31  353
25    0.31  353
26    0.23  354
27    0.24  355
28    0.30  357
29    0.23  357
30    0.23  357
⋮     ⋮     ⋮
53911 0.70  2753
53912 0.57  2753
53913 0.61  2753
53914 0.80  2753
53915 0.84  2753
53916 0.77  2753
53917 0.74  2753
53918 0.90  2753
53919 0.76  2753
53920 0.76  2753
53921 0.70  2755
53922 0.70  2755
53923 0.70  2755
53924 0.73  2756
53925 0.73  2756
53926 0.79  2756
53927 0.71  2756
53928 0.79  2756
53929 0.79  2756
53930 0.71  2756
53931 0.71  2756
53932 0.71  2756
53933 0.70  2757
53934 0.70  2757
53935 0.72  2757
53936 0.72  2757
53937 0.72  2757
53938 0.70  2757
53939 0.86  2757
53940 0.75  2757

In [15]:
dia %>% select_("carat", "price") %>% head
dia %>% select(1, 7)%>% head # 1, 7번 컬럼
dia %>% select(-c(1,7)) %>% head # 1, 7컬럼 제외
dia %>% select(-carat, -price) %>% head

  carat price
1 0.23  326
2 0.21  326
3 0.23  327
4 0.29  334
5 0.31  335
6 0.24  336

  carat price
1 0.23  326
2 0.21  326
3 0.23  327
4 0.29  334
5 0.31  335
6 0.24  336

  cut       color clarity depth table x    y    z
1 Ideal     E     SI2     61.5  55    3.95 3.98 2.43
2 Premium   E     SI1     59.8  61    3.89 3.84 2.31
3 Good      E     VS1     56.9  65    4.05 4.07 2.31
4 Premium   I     VS2     62.4  58    4.20 4.23 2.63
5 Good      J     SI2     63.3  58    4.34 4.35 2.75
6 Very Good J     VVS2    62.8  57    3.94 3.96 2.48

  cut       color clarity depth table x    y    z
1 Ideal     E     SI2     61.5  55    3.95 3.98 2.43
2 Premium   E     SI1     59.8  61    3.89 3.84 2.31
3 Good      E     VS1     56.9  65    4.05 4.07 2.31
4 Premium   I     VS2     62.4  58    4.20 4.23 2.63
5 Good      J     SI2     63.3  58    4.34 4.35 2.75
6 Very Good J     VVS2    62.8  57    3.94 3.96 2.48

In [17]:
# filter를 이용해보자. 
dia[dia$cut == "Ideal",] %>% head

  carat cut   color clarity depth table price x    y    z
1 0.23  Ideal E     SI2     61.5  55    326   3.95 3.98 2.43
2 0.23  Ideal J     VS1     62.8  56    340   3.93 3.90 2.46
3 0.31  Ideal J     SI2     62.2  54    344   4.35 4.37 2.71
4 0.30  Ideal I     SI2     62.0  54    348   4.31 4.34 2.68
5 0.33  Ideal I     SI2     61.8  55    403   4.49 4.51 2.78
6 0.33  Ideal I     SI2     61.2  56    403   4.49 4.50 2.75

In [19]:
dia %>% filter(cut == "Ideal") %>% head # 위와 동일한 결과

  carat cut   color clarity depth table price x    y    z
1 0.23  Ideal E     SI2     61.5  55    326   3.95 3.98 2.43
2 0.23  Ideal J     VS1     62.8  56    340   3.93 3.90 2.46
3 0.31  Ideal J     SI2     62.2  54    344   4.35 4.37 2.71
4 0.30  Ideal I     SI2     62.0  54    348   4.31 4.34 2.68
5 0.33  Ideal I     SI2     61.8  55    403   4.49 4.51 2.78
6 0.33  Ideal I     SI2     61.2  56    403   4.49 4.50 2.75

In [21]:
dia %>% filter(cut == "Ideal", color == "E") %>% head

  carat cut   color clarity depth table price x    y    z
1 0.23  Ideal E     SI2     61.5  55     326  3.95 3.98 2.43
2 0.26  Ideal E     VVS2    62.9  58     554  4.02 4.06 2.54
3 0.70  Ideal E     SI1     62.5  57    2757  5.70 5.72 3.57
4 0.59  Ideal E     VVS2    62.0  55    2761  5.38 5.43 3.35
5 0.74  Ideal E     SI2     62.2  56    2761  5.80 5.84 3.62
6 0.70  Ideal E     VS2     60.7  58    2762  5.73 5.76 3.49

In [22]:
dia %>% filter(cut == "Ideal", color == "E") %>% head
dia %>% filter(cut == "Ideal"& color == "E") %>% head # 결과가 동일하다.

  carat cut   color clarity depth table price x    y    z
1 0.23  Ideal E     SI2     61.5  55     326  3.95 3.98 2.43
2 0.26  Ideal E     VVS2    62.9  58     554  4.02 4.06 2.54
3 0.70  Ideal E     SI1     62.5  57    2757  5.70 5.72 3.57
4 0.59  Ideal E     VVS2    62.0  55    2761  5.38 5.43 3.35
5 0.74  Ideal E     SI2     62.2  56    2761  5.80 5.84 3.62
6 0.70  Ideal E     VS2     60.7  58    2762  5.73 5.76 3.49

  carat cut   color clarity depth table price x    y    z
1 0.23  Ideal E     SI2     61.5  55     326  3.95 3.98 2.43
2 0.26  Ideal E     VVS2    62.9  58     554  4.02 4.06 2.54
3 0.70  Ideal E     SI1     62.5  57    2757  5.70 5.72 3.57
4 0.59  Ideal E     VVS2    62.0  55    2761  5.38 5.43 3.35
5 0.74  Ideal E     SI2     62.2  56    2761  5.80 5.84 3.62
6 0.70  Ideal E     VS2     60.7  58    2762  5.73 5.76 3.49

In [24]:
dia %>% filter(cut == "Ideal" | cut == "Premium") %>% head
dia %>% filter(cut %in% c("Ideal", "Premium")) %>% head

  carat cut     color clarity depth table price x    y    z
1 0.23  Ideal   E     SI2     61.5  55    326   3.95 3.98 2.43
2 0.21  Premium E     SI1     59.8  61    326   3.89 3.84 2.31
3 0.29  Premium I     VS2     62.4  58    334   4.20 4.23 2.63
4 0.23  Ideal   J     VS1     62.8  56    340   3.93 3.90 2.46
5 0.22  Premium F     SI1     60.4  61    342   3.88 3.84 2.33
6 0.31  Ideal   J     SI2     62.2  54    344   4.35 4.37 2.71

  carat cut     color clarity depth table price x    y    z
1 0.23  Ideal   E     SI2     61.5  55    326   3.95 3.98 2.43
2 0.21  Premium E     SI1     59.8  61    326   3.89 3.84 2.31
3 0.29  Premium I     VS2     62.4  58    334   4.20 4.23 2.63
4 0.23  Ideal   J     VS1     62.8  56    340   3.93 3.90 2.46
5 0.22  Premium F     SI1     60.4  61    342   3.88 3.84 2.33
6 0.31  Ideal   J     SI2     62.2  54    344   4.35 4.37 2.71

In [27]:
dia %>% filter_("cut=='Ideal'") %>% head 
# 이렇게 하는 것을 우리가 이미 기존에 선언해놓은 변수가 있을 수 있기 때문이다.
dia %>% filter_(~cut=="Ideal") %>% head # 이렇게 할 수도 있겠다.

  carat cut   color clarity depth table price x    y    z
1 0.23  Ideal E     SI2     61.5  55    326   3.95 3.98 2.43
2 0.23  Ideal J     VS1     62.8  56    340   3.93 3.90 2.46
3 0.31  Ideal J     SI2     62.2  54    344   4.35 4.37 2.71
4 0.30  Ideal I     SI2     62.0  54    348   4.31 4.34 2.68
5 0.33  Ideal I     SI2     61.8  55    403   4.49 4.51 2.78
6 0.33  Ideal I     SI2     61.2  56    403   4.49 4.50 2.75

  carat cut   color clarity depth table price x    y    z
1 0.23  Ideal E     SI2     61.5  55    326   3.95 3.98 2.43
2 0.23  Ideal J     VS1     62.8  56    340   3.93 3.90 2.46
3 0.31  Ideal J     SI2     62.2  54    344   4.35 4.37 2.71
4 0.30  Ideal I     SI2     62.0  54    348   4.31 4.34 2.68
5 0.33  Ideal I     SI2     61.8  55    403   4.49 4.51 2.78
6 0.33  Ideal I     SI2     61.2  56    403   4.49 4.50 2.75